#!/usr/bin/env python3
"""Generate, check, and package Braids host adapters from canonical metadata.

Adapters never copy the kernel. `adapters/<host>/adapter.json` holds only the
host facts that cannot be derived, and every manifest, README, and distribution
tree is generated from it plus `braids.json`/`plugin.json`.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ADAPTERS = ROOT / "adapters"
SKILLS = ROOT / "skills"
KERNEL = SKILLS / "braids"
GENERATED = "<!-- generated by scripts/build_adapters.py; edit adapter.json instead -->"

CONFORMANCE_CHECKS = (
    "discovery", "activation", "semantic-parity", "progressive-disclosure", "authority",
    "degradation", "enforcement-truthfulness", "state-survival", "isolation", "uninstall",
)
CONFORMANCE_LINE = re.compile(
    rf"^({'|'.join(CONFORMANCE_CHECKS)}): (pass|fail|not-exercised|not-applicable) — .+$"
)
# docs/22 release threshold, expressed as the checks each status is allowed to claim.
STATUS_REQUIRES = {
    "supported": set(CONFORMANCE_CHECKS),
    "tested": {"discovery", "activation", "uninstall"},
    "experimental": set(),
    "planned": set(),
    "blocked": set(),
}
ADAPTER_REQUIRED = {
    "schema_version", "id", "adapter_version", "methodology_version", "status",
    "tested_host_versions", "surfaces", "capabilities_file", "guard_mode_default",
    "install", "disable", "uninstall", "conformance", "source_revalidated_at",
    "limitations", "package",
}


def canonical_values() -> dict[str, object]:
    metadata = json.loads((ROOT / "braids.json").read_text(encoding="utf-8"))
    plugin = json.loads((ROOT / "plugin.json").read_text(encoding="utf-8"))
    return {
        "name": plugin["name"],
        "version": plugin["version"],
        "description": plugin["description"],
        "keywords": plugin["keywords"],
        "author": plugin["author"],
        "license": plugin["license"],
        "homepage": plugin["homepage"],
        "repository": plugin["repository"],
        "methodology_version": metadata["methodology_version"],
    }


def resolve(node: object, values: dict[str, object]) -> object:
    """Replace "@key" placeholders with canonical package metadata."""
    if isinstance(node, str) and node.startswith("@"):
        key = node[1:]
        if key not in values:
            raise KeyError(f"unknown placeholder @{key}")
        return values[key]
    if isinstance(node, dict):
        return {key: resolve(value, values) for key, value in node.items()}
    if isinstance(node, list):
        return [resolve(item, values) for item in node]
    return node


def render_readme(adapter: dict, values: dict[str, object]) -> str:
    def steps(name: str) -> str:
        return "\n".join(f"{index}. {step}" for index, step in enumerate(adapter[name], 1))

    versions = ", ".join(adapter["tested_host_versions"]) or "none"
    manifests = "\n".join(f"- `{entry['path']}`" for entry in adapter["package"]["manifests"])
    conformance = "\n".join(
        f"| {line.split(':', 1)[0]} | {line.split(': ', 1)[1].split(' — ', 1)[0]} | {line.split(' — ', 1)[1]} |"
        for line in adapter["conformance"]
    )
    limitations = "\n".join(f"- {item}" for item in adapter["limitations"]) or "- none recorded"
    return f"""{GENERATED}

# Braids adapter — {adapter['id']}

| | |
|---|---|
| Status | `{adapter['status']}` |
| Adapter version | {adapter['adapter_version']} |
| Methodology version | {adapter['methodology_version']} |
| Surfaces | {', '.join(adapter['surfaces'])} |
| Host versions exercised | {versions} |
| Primary sources revalidated | {adapter['source_revalidated_at'] or 'not revalidated'} |
| Guard Mode default | off |

This adapter contains no Braids methodology. It packages the canonical
`skills/braids` kernel unchanged; `python3 scripts/build_adapters.py --dist dist`
writes the installable tree.

## Generated manifests

{manifests}

## Install

{steps('install')}

## Disable

{steps('disable')}

## Uninstall

{steps('uninstall')}

## Acceptance state (docs/22)

| Check | State | Evidence |
|---|---|---|
{conformance}

`not-exercised` means exactly that: the behaviour was not directly tested here
and is not claimed.

## Limitations

{limitations}
"""


def check_adapter(directory: Path, values: dict[str, object]) -> list[str]:
    errors: list[str] = []
    where = directory.name
    try:
        adapter = json.loads((directory / "adapter.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return [f"{where}: {exc}"]

    missing = ADAPTER_REQUIRED - set(adapter)
    if missing:
        errors.append(f"{where}: adapter.json missing {sorted(missing)}")
        return errors
    if adapter["id"] != where:
        errors.append(f"{where}: id must match the adapter directory")
    if adapter["methodology_version"] != values["methodology_version"]:
        errors.append(f"{where}: methodology version drifted from braids.json")
    if adapter["guard_mode_default"] is not False:
        errors.append(f"{where}: Guard Mode must default off")

    states: dict[str, str] = {}
    for line in adapter["conformance"]:
        if not CONFORMANCE_LINE.fullmatch(line):
            errors.append(f"{where}: malformed conformance entry {line!r}")
            continue
        check, rest = line.split(": ", 1)
        states[check] = rest.split(" — ", 1)[0]
    absent = set(CONFORMANCE_CHECKS) - set(states)
    if absent:
        errors.append(f"{where}: conformance states missing for {sorted(absent)}")
    for check in sorted(STATUS_REQUIRES.get(adapter["status"], set())):
        if states.get(check) != "pass":
            errors.append(f"{where}: status {adapter['status']} requires {check} to pass, got {states.get(check)}")
    if adapter["status"] in {"tested", "supported"} and not adapter["source_revalidated_at"]:
        errors.append(f"{where}: {adapter['status']} requires a primary-source revalidation date")
    if adapter["status"] in {"tested", "supported"} and not adapter["tested_host_versions"]:
        errors.append(f"{where}: {adapter['status']} requires an exercised host version")

    capabilities = directory / adapter["capabilities_file"]
    if not capabilities.is_file():
        errors.append(f"{where}: missing capabilities file {adapter['capabilities_file']}")
    else:
        profile = json.loads(capabilities.read_text(encoding="utf-8"))
        claimed = {entry["operation"] for entry in profile["enforcement"] if entry["status"] == "enforced"}
        if claimed and states.get("enforcement-truthfulness") != "pass":
            errors.append(f"{where}: claims enforced operations {sorted(claimed)} without an exercised enforcement test")

    package_paths = [entry["path"] for entry in adapter["package"]["manifests"]]
    package_paths += list(adapter["package"].get("extra_files", {}))
    package_paths += list(adapter["package"].get("extra_files", {}).values())
    package_paths.append(adapter["package"]["skill_target"])
    for relative in package_paths:
        if Path(relative).is_absolute() or ".." in Path(relative).parts:
            errors.append(f"{where}: package path escapes the package: {relative}")

    for entry in adapter["package"]["manifests"]:
        try:
            resolve(entry["content"], values)
        except KeyError as exc:
            errors.append(f"{where}: {exc}")

    readme = directory / "README.md"
    expected = render_readme(adapter, values)
    if not readme.is_file():
        errors.append(f"{where}: missing generated README.md")
    elif readme.read_text(encoding="utf-8") != expected:
        errors.append(f"{where}: README.md is stale; rerun scripts/build_adapters.py --write")
    return errors


def write_readmes(values: dict[str, object]) -> None:
    for directory in sorted(p for p in ADAPTERS.iterdir() if p.is_dir()):
        adapter = json.loads((directory / "adapter.json").read_text(encoding="utf-8"))
        (directory / "README.md").write_text(render_readme(adapter, values), encoding="utf-8")


def package(dist: Path, values: dict[str, object], only: str | None) -> list[str]:
    errors: list[str] = []
    for directory in sorted(p for p in ADAPTERS.iterdir() if p.is_dir()):
        if only and directory.name != only:
            continue
        adapter = json.loads((directory / "adapter.json").read_text(encoding="utf-8"))
        if adapter["status"] == "blocked":
            continue
        target = dist / directory.name
        if target.exists():
            shutil.rmtree(target)
        skill_root = target / adapter["package"]["skill_target"]
        skill_root.mkdir(parents=True, exist_ok=True)
        for skill in sorted(p for p in SKILLS.iterdir() if (p / "SKILL.md").is_file()):
            shutil.copytree(skill, skill_root / skill.name,
                            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        for entry in adapter["package"]["manifests"]:
            path = target / entry["path"]
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(resolve(entry["content"], values), indent=2) + "\n", encoding="utf-8")
        for name, source in adapter["package"].get("extra_files", {}).items():
            destination = target / name
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(directory / source, destination)
        shutil.copy2(directory / "README.md", target / "README.md")
        shutil.copy2(directory / adapter["capabilities_file"], target / "capabilities.json")
    return errors


def install_root(values: dict[str, object]) -> list[str]:
    """Write host manifests at the repository root.

    The root already holds `skills/`, so for every adapter whose package layout
    puts skills at `skills/` the repository *is* the installable plugin. Writing
    those manifests here lets a user install straight from a clone or a git
    marketplace, with no build step and still no second copy of the kernel.
    """
    written = []
    for directory in sorted(p for p in ADAPTERS.iterdir() if p.is_dir()):
        adapter = json.loads((directory / "adapter.json").read_text(encoding="utf-8"))
        if adapter["package"]["skill_target"] != "skills":
            continue
        for entry in adapter["package"]["manifests"]:
            path = ROOT / entry["path"]
            if path == ROOT / "plugin.json":
                continue  # the portable manifest is hand-owned canonical metadata
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(resolve(entry["content"], values), indent=2) + "\n", encoding="utf-8")
            written.append(entry["path"])
    return sorted(set(written))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate adapter READMEs from adapter.json.")
    parser.add_argument("--dist", type=Path, help="Assemble installable adapter trees under this directory.")
    parser.add_argument("--only", help="Restrict --dist to one adapter id.")
    parser.add_argument("--install-root", action="store_true",
                        help="Write host manifests at the repository root so a clone installs directly.")
    args = parser.parse_args()

    values = canonical_values()
    if args.write:
        write_readmes(values)
    if args.install_root:
        for path in install_root(values):
            print(f"root manifest: {path}")

    directories = sorted(p for p in ADAPTERS.iterdir() if p.is_dir())
    errors = [error for directory in directories for error in check_adapter(directory, values)]
    if not errors and args.dist:
        errors.extend(package(args.dist, values, args.only))

    if errors:
        print("\n".join(f"ERROR: {error}" for error in errors), file=sys.stderr)
        return 1
    print(f"ok: {len(directories)} adapters" + (f"; packaged to {args.dist}" if args.dist else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
